-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 13:35:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestionStock
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GestionStock` ;

-- -----------------------------------------------------
-- Schema GestionStock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestionStock` DEFAULT CHARACTER SET utf8 ;
USE `GestionStock` ;

-- -----------------------------------------------------
-- Table `GestionStock`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionStock`.`users` ;

CREATE TABLE IF NOT EXISTS `GestionStock`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(254) NOT NULL,
  `password` VARCHAR(255) NULL,
  `resetToken` VARCHAR(255) NULL,
  `admin` TINYINT NOT NULL,
  `firstCon` TINYINT NULL DEFAULT 1,
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionStock`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionStock`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `GestionStock`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `refSupplier` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `locality` VARCHAR(45) NOT NULL,
  `NPA` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `refSupplier_UNIQUE` (`refSupplier` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionStock`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionStock`.`articles` ;

CREATE TABLE IF NOT EXISTS `GestionStock`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `refArticle` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `buyPrice` DECIMAL(10,2) NOT NULL,
  `salePrice` DECIMAL(10,2) NOT NULL,
  `actualStock` INT NOT NULL,
  `minStock` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `supplier_id` INT NOT NULL DEFAULT 1,
  UNIQUE INDEX `refArticle_UNIQUE` (`refArticle` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `articlescol_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_articles_suppliers1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_articles_suppliers1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `GestionStock`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionStock`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionStock`.`orders` ;

CREATE TABLE IF NOT EXISTS `GestionStock`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateOrder` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `GestionStock`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionStock`.`stories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionStock`.`stories` ;

CREATE TABLE IF NOT EXISTS `GestionStock`.`stories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentChange` VARCHAR(255) NOT NULL,
  `dateChange` DATE NOT NULL,
  `article_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idStory_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_stories_articles1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_stories_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_stories_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `GestionStock`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stories_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `GestionStock`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionStock`.`orders_has_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionStock`.`orders_has_articles` ;

CREATE TABLE IF NOT EXISTS `GestionStock`.`orders_has_articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_has_articles_articles1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_orders_has_articles_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_articles_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `GestionStock`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_articles_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `GestionStock`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
