name: linter.yml
# Gemini help
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Super-Linter need history complet to compare the files
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5 # call action Marketplace
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Requis par Super-Linter

